version: '3.2'

services:
  database:
    restart: always
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.conf
    env_file:
      - docker/mysql.env

  app: &application_base
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    ports:
      - "3000:3000"
    volumes:
      - .:/PROJECT_NAME
      - "bundle:/usr/local/bundle"
      - node_modules:/PROJECT_NAME/node_modules
    depends_on:
      - database
    tty: true
    stdin_open: true

  webpacker:
    <<: *application_base
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - app

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  mysql-volume:
    driver: local
